---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integrationaccountsmovements
  description: "Microservicios para la consulta de los movimientos generados durante el proceso de DO IMSS y componentes complementarios como: Monitoreo Acreditación, Microservicio Movimientos Previos, Microservicio de Reporte Acreditación."
  tags:
    - microservice
    - financial
  links:
    - url: https://github.com/JCAL0199/Integrationaccountsmovements
      title: Repository
  annotations:
    backstage.io/techdocs-ref: dir:.
    endpoints/dev: https://api.dev.company1.mx/company/1/nci-bdnsarintegrationaccountsmovements
    endpoints/qa: https://api.qa.company1.mx/company/1/nci-bdnsarintegrationaccountsmovements
    endpoints/prod: https://api.company1.mx/company/1/nci-bdnsarintegrationaccountsmovements
spec:
  type: service
  owner: group:default/juan-manuel-perez
  lifecycle: production
  system: bdnsar
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: dispersion-ordinaria-imss
  description: Dispersión Ordinaria IMSS
  tags:
    - proceso-negocio
spec:
  type: negocio
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/integrationaccountsmovements
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: carga-archivo
  description: Dispersión Ordinaria IMSS/Carga Archivo -Edición
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: idc
  description: Dispersión Ordinaria IMSS/IDC
  tags:
    - sub-etapa
spec:
  type: subetapa
  lifecycle: experimental
  owner: group:default/developers
  subcomponentOf: component:default/dispersion-ordinaria-imss
